# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('death_date', models.DateField(db_index=True)),
                ('age_at_death_months', models.IntegerField(blank=True, null=True)),
                ('cause', models.CharField(blank=True, max_length=200)),
                ('vet_confirmed', models.BooleanField(default=False)),
                ('carcass_disposed', models.BooleanField(default=False)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_record', to='animals.animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mortality',
                'ordering': ['-death_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_type', models.CharField(max_length=100)),
                ('disease_targeted', models.CharField(blank=True, max_length=100)),
                ('date_administered', models.DateField(db_index=True)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to='core.staff')),
                ('animal_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vaccinations',
                'ordering': ['-date_administered'],
                'indexes': [models.Index(fields=['animal_tag', '-date_administered'], name='vaccination_animal__504aa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(blank=True, max_length=200)),
                ('symptoms', models.TextField(blank=True)),
                ('medication_given', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('treatment_date', models.DateField(db_index=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='animals.animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_records', to=settings.AUTH_USER_MODEL)),
                ('treated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_administered', to='core.staff')),
            ],
            options={
                'db_table': 'treatments',
                'ordering': ['-treatment_date'],
                'indexes': [models.Index(fields=['animal_tag', '-treatment_date'], name='treatments_animal__503fab_idx')],
            },
        ),
    ]
