# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('tag_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rfid_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('born', 'Born on Ranch'), ('purchased', 'Purchased'), ('imported', 'Imported')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('dead', 'Dead'), ('missing', 'Missing')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_dam', to='animals.animal')),
            ],
            options={
                'db_table': 'animals',
                'ordering': ['-created_at'],
            },
        ),
    ]
