# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='core.ranch'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sire_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_sire', to='animals.animal'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species', 'status'], name='animals_species_23c577_idx'),
        ),
    ]
