# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semen_batch_id', models.CharField(blank=True, max_length=100)),
                ('heat_detected_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('natural', 'Natural Service'), ('artificial_insemination', 'Artificial Insemination')], max_length=30)),
                ('pregnancy_confirmed', models.CharField(choices=[('pending', 'Pending'), ('yes', 'Confirmed Pregnant'), ('no', 'Not Pregnant')], default='pending', max_length=20)),
                ('pregnancy_check_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('live_birth', 'Live Birth'), ('stillbirth', 'Stillbirth'), ('abortion', 'Abortion'), ('failed_conception', 'Failed Conception')], max_length=30)),
                ('number_of_offspring', models.IntegerField(default=1)),
                ('offspring_tags', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('female_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_as_dam', to='animals.animal')),
                ('male_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_as_sire', to='animals.animal')),
            ],
            options={
                'db_table': 'breeding_events',
                'ordering': ['-service_date'],
            },
        ),
    ]
