# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingevent',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='breedingevent',
            index=models.Index(fields=['female_tag', '-service_date'], name='breeding_ev_female__1bbbed_idx'),
        ),
    ]
