# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('from_zone', models.CharField(blank=True, max_length=100)),
                ('to_zone', models.CharField(max_length=100)),
                ('movement_date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='animals.animal')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_performed', to='core.staff')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movement_logs',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='RFIDScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfid_code', models.CharField(db_index=True, max_length=100)),
                ('gate_id', models.CharField(blank=True, max_length=50)),
                ('scan_timestamp', models.DateTimeField(db_index=True)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_scans', to='animals.animal')),
            ],
            options={
                'db_table': 'rfid_scan_logs',
                'ordering': ['-scan_timestamp'],
                'indexes': [models.Index(fields=['gate_id', '-scan_timestamp'], name='rfid_scan_l_gate_id_bc4f2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HerdCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_date', models.DateField(db_index=True)),
                ('species', models.CharField(max_length=20)),
                ('expected_count', models.IntegerField()),
                ('actual_count', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('grazing_zone', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counts_performed', to='core.staff')),
                ('ranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herd_counts', to='core.ranch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'herd_counts',
                'ordering': ['-count_date'],
                'indexes': [models.Index(fields=['ranch', '-count_date'], name='herd_counts_ranch_i_49aa2f_idx')],
            },
        ),
    ]
