# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
