# Generated by Django 4.2.9 on 2026-02-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='ranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.ranch'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['ranch', 'metric_type', '-calculation_date'], name='system_metr_ranch_i_c280c2_idx'),
        ),
    ]
